#ifndef HW_VOLLEY_412_H_
#define HW_VOLLEY_412_H_
/*-----------------------------------------------------------------------------
	Copyright 2015 Benjamin Vedder	benjamin@vedder.se

	This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
-----------------------------------------------------------------------------*/

#define HW_NAME "VOLLEY_412"
#define HW_MAJOR 4
#define HW_MINOR 12

// Macros
#define ENABLE_GATE() palSetPad(GPIOC, 10)
#define DISABLE_GATE() palClearPad(GPIOC, 10)
#define DCCAL_ON() palSetPad(GPIOB, 12)
#define DCCAL_OFF() palClearPad(GPIOB, 12)
#define IS_DRV_FAULT() (!palReadPad(GPIOC, 12))

#define LED_GREEN_ON() palSetPad(GPIOC, 4)
#define LED_GREEN_OFF() palClearPad(GPIOC, 4)
#define LED_RED_ON() palSetPad(GPIOC, 5)
#define LED_RED_OFF() palClearPad(GPIOC, 5)

// Used to autoconfigure CAN addresses
#define CAN_ID1() palReadPad(GPIOC, 1)
#define CAN_ID2() palReadPad(GPIOC, 3)

/*
 * ADC Vector
 *
 * 0:	IN0		SENS0
 * 1:	IN1		SENS2
 * 2:	IN2		SENS3
 * 3:	IN8		CURR2
 * 4:	IN9		CURR1
 * 5:	IN3		TEMP_MOSFET
 * 6:	Vrefint
 * 7:	IN6		ADC_EXT2
 * 8:	IN12	AN_IN
 * 9:	IN4		TX_SDA_NSS
 * 10:	IN5     ADC_EXT
 * 11:	IN3 	TEMP_MOTOR
 */

#define HW_ADC_CHANNELS 12
#define HW_ADC_INJ_CHANNELS 2
#define HW_ADC_NBR_CONV 4

// ADC Indexes
// There was an error in the original VESC that was corrected on our design.
// SENSE3 and SENSE1 have been swapped to match the new hardware.
#define ADC_IND_SENS1 0
#define ADC_IND_SENS2 1
#define ADC_IND_SENS3 2
#define ADC_IND_CURR1 4
#define ADC_IND_CURR2 3
#define ADC_IND_VIN_SENS 8
#define ADC_IND_EXT 10
#define ADC_IND_EXT2 7
#define ADC_IND_TEMP_MOS 5
#define ADC_IND_TEMP_MOTOR 11
#define ADC_IND_VREFINT 6

// ADC macros and settings

// Component parameters (can be overridden)
#ifndef V_REG
#define V_REG 3.3
#endif
#ifndef VIN_R1
#define VIN_R1 39000.0
#endif
#ifndef VIN_R2
#define VIN_R2 2200.0
#endif
#ifndef CURRENT_AMP_GAIN
#define CURRENT_AMP_GAIN 10.0
#endif
#ifndef CURRENT_SHUNT_RES
#define CURRENT_SHUNT_RES 0.005
#endif

// Input voltage
#define GET_INPUT_VOLTAGE() ((V_REG / 4095.0) * (float)ADC_Value[ADC_IND_VIN_SENS] * ((VIN_R1 + VIN_R2) / VIN_R2))

// Voltage on ADC channel
#define ADC_VOLTS(ch) ((float)ADC_Value[ch] / 4095.0 * V_REG)

// NTC Termistors
#define NTC_RES(adc_val) ((4095.0 * 10000.0) / adc_val - 10000.0)
#define NTC_TEMP(adc_ind) (1.0 / ((logf(NTC_RES(ADC_Value[adc_ind]) / 10000.0) / 3434.0) + (1.0 / 298.15)) - 273.15)

#define NTC_RES_MOTOR(adc_val) (10000.0 / ((4095.0 / (float)adc_val) - 1.0)) // Motor temp sensor on low side
#define NTC_TEMP_MOTOR(beta) (1.0 / ((logf(NTC_RES_MOTOR(ADC_Value[ADC_IND_TEMP_MOTOR]) / 10000.0) / beta) + (1.0 / 298.15)) - 273.15)

// Double samples in beginning and end for positive current measurement.
// Useful when the shunt sense traces have noise that causes offset.
#ifndef CURR1_DOUBLE_SAMPLE
#define CURR1_DOUBLE_SAMPLE 0
#endif
#ifndef CURR2_DOUBLE_SAMPLE
#define CURR2_DOUBLE_SAMPLE 0
#endif

// UART Peripheral
#define HW_UART_DEV SD6
#define HW_UART_GPIO_AF GPIO_AF_USART6
#define HW_UART_TX_PORT GPIOC
#define HW_UART_TX_PIN 6
#define HW_UART_RX_PORT GPIOC
#define HW_UART_RX_PIN 7

// ICU Peripheral for servo decoding
#define HW_ICU_TIMER TIM3
#define HW_ICU_TIM_CLK_EN() RCC_APB1PeriphClockCmd(RCC_APB1Periph_TIM3, ENABLE)
#define HW_ICU_DEV ICUD3
#define HW_ICU_CHANNEL ICU_CHANNEL_2
#define HW_ICU_GPIO_AF GPIO_AF_TIM3
#define HW_ICU_GPIO GPIOB
#define HW_ICU_PIN 5

// I2C Peripheral
#define HW_I2C_DEV I2CD2
#define HW_I2C_GPIO_AF GPIO_AF_I2C2
#define HW_I2C_SCL_PORT GPIOB
#define HW_I2C_SCL_PIN 10
#define HW_I2C_SDA_PORT GPIOB
#define HW_I2C_SDA_PIN 11

// Hall/encoder pins
#define HW_HALL_ENC_GPIO1 GPIOB
#define HW_HALL_ENC_PIN1 6
#define HW_HALL_ENC_GPIO2 GPIOB
#define HW_HALL_ENC_PIN2 7
#define HW_HALL_ENC_GPIO3 GPIOC
#define HW_HALL_ENC_PIN3 11
#define HW_ENC_TIM TIM4
#define HW_ENC_TIM_AF GPIO_AF_TIM4
#define HW_ENC_TIM_CLK_EN() RCC_APB1PeriphClockCmd(RCC_APB1Periph_TIM4, ENABLE)
#define HW_ENC_EXTI_PORTSRC EXTI_PortSourceGPIOC
#define HW_ENC_EXTI_PINSRC EXTI_PinSource11
#define HW_ENC_EXTI_CH EXTI15_10_IRQn
#define HW_ENC_EXTI_LINE EXTI_Line11
#define HW_ENC_EXTI_ISR_VEC EXTI15_10_IRQHandler
#define HW_ENC_TIM_ISR_CH TIM4_IRQn
#define HW_ENC_TIM_ISR_VEC TIM4_IRQHandler

// SPI pins
#define HW_SPI_DEV SPID1
#define HW_SPI_GPIO_AF GPIO_AF_SPI1
#define HW_SPI_PORT_NSS GPIOA
#define HW_SPI_PIN_NSS 4
#define HW_SPI_PORT_SCK GPIOA
#define HW_SPI_PIN_SCK 5
#define HW_SPI_PORT_MOSI GPIOA
#define HW_SPI_PIN_MOSI 7
#define HW_SPI_PORT_MISO GPIOA
#define HW_SPI_PIN_MISO 6

// Hardware IDs
// Top: PC3 = 0, PC1 = 0 (Default ID = 10d)
// Left: PC3 = 0, PC1 = 1 (Default ID = 11d)
// Right: PC3 = 1, PC1 = 0 (Default ID = 12d)
// Unused: PC3 = 1, PC1 = 1 (Default ID = 13d)
#define HW_DEFAULT_ID hw_id_from_pins()
#define HW_ID_PIN_GPIOS_VOLLEY GPIOC, GPIOC
#define HW_ID_PIN_PINS_VOLLEY 1, 3

// Measurement macros
#define ADC_V_L1 ADC_Value[ADC_IND_SENS1]
#define ADC_V_L2 ADC_Value[ADC_IND_SENS2]
#define ADC_V_L3 ADC_Value[ADC_IND_SENS3]
#define ADC_V_ZERO (ADC_Value[ADC_IND_VIN_SENS] / 2)

// Macros
#define READ_HALL1() palReadPad(HW_HALL_ENC_GPIO1, HW_HALL_ENC_PIN1)
#define READ_HALL2() palReadPad(HW_HALL_ENC_GPIO2, HW_HALL_ENC_PIN2)
#define READ_HALL3() palReadPad(HW_HALL_ENC_GPIO3, HW_HALL_ENC_PIN3)

// Setting limits
#define HW_LIM_CURRENT -100.0, 100.0
#define HW_LIM_CURRENT_IN -100.0, 100.0
#define HW_LIM_CURRENT_ABS 0.0, 150.0
#define HW_LIM_VIN 6.0, 57.0
#define HW_LIM_ERPM -200e3, 200e3
#define HW_LIM_DUTY_MIN 0.0, 0.1
#define HW_LIM_DUTY_MAX 0.0, 0.95
#define HW_LIM_TEMP_FET -40.0, 110.0

// App Config
#define APPCONF_APP_TO_USE APP_NONE
#define APPCONF_CONTROLLER_ID HW_DEFAULT_ID
#define APPCONF_TIMEOUT_MSEC 250
#define APPCONF_SEND_CAN_STATUS CAN_STATUS_1_2_3_4_5
#define APPCONF_SEND_CAN_STATUS_RATE_HZ 10
#define APPCONF_CAN_BAUD_RATE CAN_BAUD_1M
#define APPCONF_PAIRING_DONE false
#define APPCONF_PERMANENT_UART_ENABLED false
#define APPCONF_SHUTDOWN_MODE SHUTDOWN_MODE_ALWAYS_ON
#define APPCONF_CAN_MODE CAN_MODE_VESC
#define APPCONF_UAVCAN_ESC_INDEX 0
#define APPCONF_UAVCAN_RAW_MODE UAVCAN_RAW_MODE_CURRENT
#define APPCONF_UAVCAN_RAW_RPM_MAX 50000.0
#define APPCONF_SERVO_OUT_ENABLE false
#define APPCONF_KILL_SW_MODE KILL_SW_MODE_DISABLED
#define APPCONF_BALANCE_BRAKE_CURRENT 0.0
#define APPCONF_PPM_CTRL_TYPE PPM_CTRL_TYPE_NONE
#define APPCONF_PPM_PID_MAX_ERPM 15000
#define APPCONF_PPM_HYST 0.15
#define APPCONF_PPM_PULSE_START 1.0
#define APPCONF_PPM_PULSE_END 2.0
#define APPCONF_PPM_PULSE_CENTER 1.5
#define APPCONF_PPM_MEDIAN_FILTER true
#define APPCONF_PPM_SAFE_START true
#define APPCONF_PPM_THROTTLE_EXP 0.0
#define APPCONF_PPM_THROTTLE_EXP_BRAKE 0.0
#define APPCONF_PPM_THROTTLE_EXP_MODE THR_EXP_POLY
#define APPCONF_PPM_RAMP_TIME_POS 0.4
#define APPCONF_PPM_RAMP_TIME_NEG 0.2
#define APPCONF_PPM_MULTI_ESC true
#define APPCONF_PPM_TC false
#define APPCONF_PPM_TC_MAX_DIFF 3000.0
#define APPCONF_PPM_MAX_ERPM_FOR_DIR 4000.0
#define APPCONF_PPM_SMART_REV_MAX_DUTY 0.07
#define APPCONF_PPM_SMART_REV_RAMP_TIME 3.0
#define APPCONF_ADC_CTRL_TYPE ADC_CTRL_TYPE_NONE
#define APPCONF_ADC_HYST 0.15
#define APPCONF_ADC_VOLTAGE_START 0.9
#define APPCONF_ADC_VOLTAGE_END 3.0
#define APPCONF_ADC_VOLTAGE_CENTER 2.0
#define APPCONF_ADC_VOLTAGE2_START 0.9
#define APPCONF_ADC_VOLTAGE2_END 3.0
#define APPCONF_ADC_USE_FILTER true
#define APPCONF_ADC_SAFE_START true
#define APPCONF_ADC_CC_BUTTON_INVERTED false
#define APPCONF_ADC_REV_BUTTON_INVERTED false
#define APPCONF_ADC_VOLTAGE_INVERTED false
#define APPCONF_ADC_VOLTAGE2_INVERTED false
#define APPCONF_ADC_THROTTLE_EXP 0.0
#define APPCONF_ADC_THROTTLE_EXP_BRAKE 0.0
#define APPCONF_ADC_THROTTLE_EXP_MODE THR_EXP_POLY
#define APPCONF_ADC_RAMP_TIME_POS 0.3
#define APPCONF_ADC_RAMP_TIME_NEG 0.1
#define APPCONF_ADC_MULTI_ESC true
#define APPCONF_ADC_TC false
#define APPCONF_ADC_TC_MAX_DIFF 3000.0
#define APPCONF_ADC_UPDATE_RATE_HZ 500
#define APPCONF_UART_BAUDRATE 115200
#define APPCONF_CHUK_CTRL_TYPE CHUK_CTRL_TYPE_NONE
#define APPCONF_CHUK_HYST 0.15
#define APPCONF_CHUK_RAMP_TIME_POS 0.4
#define APPCONF_CHUK_RAMP_TIME_NEG 0.2
#define APPCONF_STICK_ERPM_PER_S_IN_CC 3000.0
#define APPCONF_CHUK_THROTTLE_EXP 0.0
#define APPCONF_CHUK_THROTTLE_EXP_BRAKE 0.0
#define APPCONF_CHUK_THROTTLE_EXP_MODE THR_EXP_POLY
#define APPCONF_CHUK_MULTI_ESC true
#define APPCONF_CHUK_TC false
#define APPCONF_CHUK_TC_MAX_DIFF 3000.0
#define APPCONF_CHUK_USE_SMART_REV true
#define APPCONF_CHUK_SMART_REV_MAX_DUTY 0.07
#define APPCONF_CHUK_SMART_REV_RAMP_TIME 3.0
#define APPCONF_NRF_SPEED NRF_SPEED_1M
#define APPCONF_NRF_POWER NRF_POWER_OFF
#define APPCONF_NRF_CRC NRF_CRC_1B
#define APPCONF_NRF_RETR_DELAY NRF_RETR_DELAY_250US
#define APPCONF_NRF_RETRIES 3
#define APPCONF_NRF_CHANNEL 76
#define APPCONF_NRF_ADDR_B0 0xC6
#define APPCONF_NRF_ADDR_B1 0xC7
#define APPCONF_NRF_ADDR_B2 0x0
#define APPCONF_NRF_SEND_CRC_ACK true
#define APPCONF_BALANCE_KP 0.0
#define APPCONF_BALANCE_KI 0.0
#define APPCONF_BALANCE_KD 0.0
#define APPCONF_BALANCE_HERTZ 1000
#define APPCONF_BALANCE_LOOP_TIME_FILTER 0
#define APPCONF_BALANCE_FAULT_PITCH 20
#define APPCONF_BALANCE_FAULT_ROLL 45
#define APPCONF_BALANCE_FAULT_DUTY 0.9
#define APPCONF_BALANCE_FAULT_ADC1 0.0
#define APPCONF_BALANCE_FAULT_ADC2 0.0
#define APPCONF_BALANCE_FAULT_DELAY_PITCH 0
#define APPCONF_BALANCE_FAULT_DELAY_ROLL 0
#define APPCONF_BALANCE_FAULT_DELAY_DUTY 0
#define APPCONF_BALANCE_FAULT_DELAY_SWITCH_HALF 0
#define APPCONF_BALANCE_FAULT_DELAY_SWITCH_FULL 0
#define APPCONF_BALANCE_FAULT_ADC_HALF_ERPM 1000
#define APPCONF_BALANCE_TILTBACK_DUTY_ANGLE 10.0
#define APPCONF_BALANCE_TILTBACK_DUTY_SPEED 3.0
#define APPCONF_BALANCE_TILTBACK_DUTY 0.75
#define APPCONF_BALANCE_TILTBACK_HV_ANGLE 10
#define APPCONF_BALANCE_TILTBACK_HV_SPEED 3.0
#define APPCONF_BALANCE_TILTBACK_HV 200.0
#define APPCONF_BALANCE_TILTBACK_LV_ANGLE 10.0
#define APPCONF_BALANCE_TILTBACK_LV_SPEED 3.0
#define APPCONF_BALANCE_TILTBACK_LV 0.0
#define APPCONF_BALANCE_TILTBACK_RETURN_SPEED 2.0
#define APPCONF_BALANCE_TILTBACK_CONSTANT 0.0
#define APPCONF_BALANCE_TILTBACK_CONSTANT_ERPM 500
#define APPCONF_BALANCE_TILTBACK_VARIABLE 0.0
#define APPCONF_BALANCE_TILTBACK_VARIABLE_MAX 0.0
#define APPCONF_BALANCE_NOSEANGLING_SPEED 3.0
#define APPCONF_BALANCE_STARTUP_PITCH_TOLERANCE 20.0
#define APPCONF_BALANCE_STARTUP_ROLL_TOLERANCE 8.0
#define APPCONF_BALANCE_STARTUP_SPEED 30.0
#define APPCONF_BALANCE_DEADZONE 0.0
#define APPCONF_BALANCE_MULTI_ESC false
#define APPCONF_BALANCE_YAW_KP 0.0
#define APPCONF_BALANCE_YAW_KI 0.0
#define APPCONF_BALANCE_YAW_KD 0.0
#define APPCONF_BALANCE_ROLL_STEER_KP 0.0
#define APPCONF_BALANCE_ROLL_STEER_ERPM_KP 0.0
#define APPCONF_BALANCE_BRAKE_CURRENT 0.0
#define APPCONF_BALANCE_BRAKE_TIMEOUT 10
#define APPCONF_BALANCE_YAW_CURRENT_CLAMP 0.0
#define APPCONF_BALANCE_KD_PT1_LOWPASS_FREQUENCY 0
#define APPCONF_BALANCE_KD_PT1_HIGHPASS_FREQUENCY 0
#define APPCONF_BALANCE_KD_BIQUAD_LOWPASS 0
#define APPCONF_BALANCE_KD_BIQUAD_HIGHPASS 0
#define APPCONF_BALANCE_BOOSTER_ANGLE 8
#define APPCONF_BALANCE_BOOSTER_RAMP 1
#define APPCONF_BALANCE_BOOSTER_CURRENT 0
#define APPCONF_BALANCE_TORQUETILT_START_CURRENT 10
#define APPCONF_BALANCE_TORQUETILT_ANGLE_LIMIT 5
#define APPCONF_BALANCE_TORQUETILT_ON_SPEED 5
#define APPCONF_BALANCE_TORQUETILT_OFF_SPEED 3
#define APPCONF_BALANCE_TORQUETILT_STRENGTH 0.0
#define APPCONF_BALANCE_TORQUETILT_FILTER 2.0
#define APPCONF_BALANCE_TURNTILT_STRENGTH 0
#define APPCONF_BALANCE_TURNTILT_ANGLE_LIMIT 5
#define APPCONF_BALANCE_TURNTILT_START_ANGLE 1
#define APPCONF_BALANCE_TURNTILT_START_ERPM 100
#define APPCONF_BALANCE_TURNTILT_SPEED 5
#define APPCONF_BALANCE_TURNTILT_ERPM_BOOST 20
#define APPCONF_BALANCE_TURNTILT_ERPM_BOOST_END 20000
#define APPCONF_PAS_CTRL_TYPE PAS_CTRL_TYPE_NONE
#define APPCONF_PAS_SENSOR_TYPE PAS_SENSOR_TYPE_QUADRATURE
#define APPCONF_PAS_PEDAL_RPM_START 10.0
#define APPCONF_PAS_PEDAL_RPM_END 180.0
#define APPCONF_PAS_INVERT_PEDAL_DIRECTION false
#define APPCONF_PAS_MAGNETS 24
#define APPCONF_PAS_USE_FILTER true
#define APPCONF_PAS_CURRENT_SCALING 0.1
#define APPCONF_PAS_RAMP_TIME_POS 0.6
#define APPCONF_PAS_RAMP_TIME_NEG 0.3
#define APPCONF_PAS_UPDATE_RATE_HZ 500
#define APPCONF_IMU_TYPE IMU_TYPE_OFF
#define APPCONF_IMU_AHRS_MODE AHRS_MODE_MADGWICK
#define APPCONF_IMU_SAMPLE_RATE_HZ 200
#define APPCONF_IMU_ACCEL_CONFIDENCE_DECAY 1.0
#define APPCONF_IMU_MAHONY_KP 0.3
#define APPCONF_IMU_MAHONY_KI 0.0
#define APPCONF_IMU_MADGWICK_BETA 0.1
#define APPCONF_IMU_ROT_ROLL 0.0
#define APPCONF_IMU_ROT_PITCH 0.0
#define APPCONF_IMU_ROT_YAW 0.0
#define APPCONF_IMU_A_OFFSET_0 0.0
#define APPCONF_IMU_A_OFFSET_1 0.0
#define APPCONF_IMU_A_OFFSET_2 0.0
#define APPCONF_IMU_G_OFFSET_0 0.0
#define APPCONF_IMU_G_OFFSET_1 0.0
#define APPCONF_IMU_G_OFFSET_2 0.0

// Motor Config
#define MCCONF_PWM_MODE PWM_MODE_SYNCHRONOUS
#define MCCONF_COMM_MODE COMM_MODE_INTEGRATE
#define MCCONF_DEFAULT_MOTOR_TYPE MOTOR_TYPE_FOC
#define MCCONF_SENSOR_MODE FOC_SENSOR_MODE_HALL
#define MCCONF_L_CURRENT_MAX 15
#define MCCONF_L_CURRENT_MIN -15
#define MCCONF_L_IN_CURRENT_MAX 5
#define MCCONF_L_IN_CURRENT_MIN -5
#define MCCONF_L_MAX_ABS_CURRENT 30
#define MCCONF_L_RPM_MIN -28000
#define MCCONF_L_RPM_MAX 28000
#define MCCONF_L_RPM_START 1
#define MCCONF_L_CURR_MAX_RPM_FBRAKE 300
#define MCCONF_L_CURR_MAX_RPM_FBRAKE_CC 1500
#define MCCONF_L_MIN_VOLTAGE 18
#define MCCONF_L_MAX_VOLTAGE 57
#define MCCONF_L_BATTERY_CUT_START 28
#define MCCONF_L_BATTERY_CUT_END 25
#define MCCONF_L_SLOW_ABS_OVERCURRENT 1
#define MCCONF_L_LIM_TEMP_FET_START 85
#define MCCONF_L_LIM_TEMP_FET_END 100
#define MCCONF_L_LIM_TEMP_MOTOR_START 190
#define MCCONF_L_LIM_TEMP_MOTOR_END 190
#define MCCONF_L_LIM_TEMP_ACCEL_DEC 0
#define MCCONF_L_MIN_DUTY 0.005
#define MCCONF_L_MAX_DUTY 0.95
#define MCCONF_L_WATT_MAX 650
#define MCCONF_L_WATT_MIN -650
#define MCCONF_L_CURRENT_MAX_SCALE 1
#define MCCONF_L_CURRENT_MIN_SCALE 1
#define MCCONF_L_DUTY_START 1
#define MCCONF_SL_MIN_RPM 150
#define MCCONF_SL_MIN_ERPM_CYCLE_INT_LIMIT 1100
#define MCCONF_SL_MAX_FB_CURR_DIR_CHANGE 10
#define MCCONF_SL_CYCLE_INT_LIMIT 62
#define MCCONF_SL_PHASE_ADVANCE_AT_BR 0.8
#define MCCONF_SL_CYCLE_INT_BR 80000
#define MCCONF_SL_BEMF_COUPLING_K 600
#define MCCONF_HALL_TAB_0 -1
#define MCCONF_HALL_TAB_1 1
#define MCCONF_HALL_TAB_2 3
#define MCCONF_HALL_TAB_3 2
#define MCCONF_HALL_TAB_4 5
#define MCCONF_HALL_TAB_5 6
#define MCCONF_HALL_TAB_6 4
#define MCCONF_HALL_TAB_7 -1
#define MCCONF_HALL_ERPM 2000
#define MCCONF_FOC_CURRENT_KP 0.1438
#define MCCONF_FOC_CURRENT_KI 84.7
#define MCCONF_FOC_F_ZV 40000
#define MCCONF_FOC_DT_US 0.12
#define MCCONF_FOC_ENCODER_INVERTED 0
#define MCCONF_FOC_ENCODER_OFFSET 180
#define MCCONF_FOC_ENCODER_RATIO 7
#define MCCONF_FOC_ENCODER_SIN_GAIN 1
#define MCCONF_FOC_ENCODER_COS_GAIN 1
#define MCCONF_FOC_ENCODER_SIN_OFFSET 1.65
#define MCCONF_FOC_ENCODER_COS_OFFSET 1.65
#define MCCONF_FOC_ENCODER_SINCOS_FILTER 0.5
#define MCCONF_FOC_SENSOR_MODE 2
#define MCCONF_FOC_PLL_KP 500
#define MCCONF_FOC_PLL_KI 15000
#define MCCONF_FOC_MOTOR_L 0.00014379
#define MCCONF_FOC_MOTOR_LD_LQ_DIFF 0.00002678
#define MCCONF_FOC_MOTOR_R 0.0847
#define MCCONF_FOC_MOTOR_FLUX_LINKAGE 0.006725
#define MCCONF_FOC_OBSERVER_GAIN 2.211e+07
#define MCCONF_FOC_OBSERVER_GAIN_SLOW 0.05
#define MCCONF_FOC_OBSERVER_OFFSET -1
#define MCCONF_FOC_DUTY_DOWNRAMP_KP 10
#define MCCONF_FOC_DUTY_DOWNRAMP_KI 200
#define MCCONF_FOC_OPENLOOP_RPM 1500
#define MCCONF_FOC_OPENLOOP_RPM_LOW 0
#define MCCONF_FOC_D_GAIN_SCALE_START 0.9
#define MCCONF_FOC_D_GAIN_SCALE_MAX_MOD 0.2
#define MCCONF_FOC_SL_OPENLOOP_HYST 0.1
#define MCCONF_FOC_SL_OPENLOOP_T_LOCK 0
#define MCCONF_FOC_SL_OPENLOOP_T_RAMP 0.1
#define MCCONF_FOC_SL_OPENLOOP_TIME 0.05
#define MCCONF_FOC_HALL_TAB_0 255
#define MCCONF_FOC_HALL_TAB_1 131
#define MCCONF_FOC_HALL_TAB_2 198
#define MCCONF_FOC_HALL_TAB_3 165
#define MCCONF_FOC_HALL_TAB_4 66
#define MCCONF_FOC_HALL_TAB_5 99
#define MCCONF_FOC_HALL_TAB_6 31
#define MCCONF_FOC_HALL_TAB_7 255
#define MCCONF_FOC_HALL_INTERP_ERPM 500
#define MCCONF_FOC_SL_ERPM 2500
#define MCCONF_FOC_SAMPLE_V0_V7 0
#define MCCONF_FOC_SAMPLE_HIGH_CURRENT 0
#define MCCONF_FOC_SAT_COMP 0
#define MCCONF_FOC_TEMP_COMP 0
#define MCCONF_FOC_TEMP_COMP_BASE_TEMP 25
#define MCCONF_FOC_CURRENT_FILTER_CONST 0.1
#define MCCONF_FOC_CC_DECOUPLING 2
#define MCCONF_FOC_OBSERVER_TYPE 0
#define MCCONF_FOC_HFI_VOLTAGE_START 20
#define MCCONF_FOC_HFI_VOLTAGE_RUN 4
#define MCCONF_FOC_HFI_VOLTAGE_MAX 10
#define MCCONF_FOC_SL_ERPM_HFI 2000
#define MCCONF_FOC_HFI_START_SAMPLES 15
#define MCCONF_FOC_HFI_OBS_OVR_SEC 0.001
#define MCCONF_FOC_HFI_SAMPLES 1
#define MCCONF_FOC_OFFSETS_CAL_ON_BOOT 1
#define MCCONF_FOC_OFFSETS_CURRENT_0 2051.86
#define MCCONF_FOC_OFFSETS_CURRENT_1 2052.84
#define MCCONF_FOC_OFFSETS_CURRENT_2 0
#define MCCONF_FOC_OFFSETS_VOLTAGE_0 0.003
#define MCCONF_FOC_OFFSETS_VOLTAGE_1 0.0003
#define MCCONF_FOC_OFFSETS_VOLTAGE_2 0.0026
#define MCCONF_FOC_OFFSETS_VOLTAGE_UNDRIVEN_0 0
#define MCCONF_FOC_OFFSETS_VOLTAGE_UNDRIVEN_1 0
#define MCCONF_FOC_OFFSETS_VOLTAGE_UNDRIVEN_2 0
#define MCCONF_FOC_PHASE_FILTER_ENABLE 1
#define MCCONF_FOC_PHASE_FILTER_MAX_ERPM 4000
#define MCCONF_FOC_MTPA_MODE 0
#define MCCONF_FOC_FW_CURRENT_MAX 0
#define MCCONF_FOC_FW_DUTY_START 0.9
#define MCCONF_FOC_FW_RAMP_TIME 0.2
#define MCCONF_FOC_FW_Q_CURRENT_FACTOR 0.02
#define MCCONF_GPD_BUFFER_NOTIFY_LEFT 200
#define MCCONF_GPD_BUFFER_INTERPOL 0
#define MCCONF_GPD_CURRENT_FILTER_CONST 0.1
#define MCCONF_GPD_CURRENT_KP 0.03
#define MCCONF_GPD_CURRENT_KI 50
#define MCCONF_SP_PID_LOOP_RATE 5
#define MCCONF_S_PID_KP 0.01
#define MCCONF_S_PID_KI 0.01
#define MCCONF_S_PID_KD 0
#define MCCONF_S_PID_KD_FILTER 0.2
#define MCCONF_S_PID_MIN_RPM 0
#define MCCONF_S_PID_ALLOW_BRAKING 1
#define MCCONF_S_PID_RAMP_ERPMS_S -1
#define MCCONF_P_PID_KP 0.025
#define MCCONF_P_PID_KI 0
#define MCCONF_P_PID_KD 0
#define MCCONF_P_PID_OFFSET 0
#define MCCONF_P_PID_KD_PROC 0.00035
#define MCCONF_P_PID_KD_FILTER 0.2
#define MCCONF_P_PID_ANG_DIV 1
#define MCCONF_P_PID_GAIN_DEC_ANGLE 0
#define MCCONF_CC_STARTUP_BOOST_DUTY 0.01
#define MCCONF_CC_MIN_CURRENT 0.05
#define MCCONF_CC_GAIN 0.0046
#define MCCONF_CC_RAMP_STEP 0.04
#define MCCONF_M_FAULT_STOP_TIME 500
#define MCCONF_M_RAMP_STEP 0.02
#define MCCONF_M_CURRENT_BACKOFF_GAIN 0.5
#define MCCONF_M_ENCODER_COUNTS 8192
#define MCCONF_M_SENSOR_PORT_MODE 0
#define MCCONF_M_INVERT_DIRECTION 1
#define MCCONF_M_DRV8301_OC_MODE 0
#define MCCONF_M_DRV8301_OC_ADJ 16
#define MCCONF_M_BLDC_F_SW_MIN 3000
#define MCCONF_M_BLDC_F_SW_MAX 35000
#define MCCONF_M_DC_F_SW 25000
#define MCCONF_M_NTC_MOTOR_BETA 3380
#define MCCONF_M_OUT_AUX_MODE 0
#define MCCONF_M_MOTOR_TEMP_SENS_TYPE 0
#define MCCONF_M_PTC_MOTOR_COEFF 0.61
#define MCCONF_M_HALL_EXTRA_SAMPLES 1
#define MCCONF_SI_MOTOR_POLES 8
#define MCCONF_SI_GEAR_RATIO 1
#define MCCONF_SI_WHEEL_DIAMETER 0.127
#define MCCONF_SI_BATTERY_TYPE 0
#define MCCONF_SI_BATTERY_CELLS 10
#define MCCONF_SI_BATTERY_AH 12
#define MCCONF_SI_MOTOR_NL_CURRENT 1.5
#define MCCONF_BMS_TYPE 0
#define MCCONF_BMS_T_LIMIT_START 45
#define MCCONF_BMS_T_LIMIT_END 65
#define MCCONF_BMS_SOC_LIMIT_START 0.05
#define MCCONF_BMS_SOC_LIMIT_END 0
#define MCCONF_BMS_FWD_CAN_MODE 0

#endif /* HW_VOLLEY_412_H_ */
